spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authentication-server
    username: admin
    password: asd123
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

app:
  security:
    jwt:
      private-key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEpQIBAAKCAQEAxXw9WTwgzNvdNYSdgjdfnUWgfeVfKRp3JewTWKxbRbeiCVjw
        5pcj5t9yntCG5KLZU4pVjPppEl3fLa/jbYuprPLPwqtkgcMK7drrWlLEdppD0XBv
        MRp1ZmYalWdHJOpY/xFD8w3NavXNAPJULD88MBIR/99zc9DKnfp88u+SkHjiVHLi
        dpR5OQPP3sqiS+bsPcaBWRvHQ7r1yFe6PAyWhTNAMr62s+HbjkV2u7i1u8Lc6iul
        VhD2riM4oTndjoN8KRsf/G3nOSVvbCA0CCv9Tnk6H7eeZVh9o061LQxQ64hWXsCQ
        5lcitA1Fm+xjkrIlc/TQe38Z3WD8VD48rDAWLwIDAQABAoIBAQCZ5PJt2pR48BEX
        Rovz0LD6/ypNUXRxtIULEUgWPuI1lx93h07bcwZwQMqyhi/IdjtDhbabUPyWan6j
        vMBPOpn0A5fxzNxa3qJirsnfLkaZYifdS2/q5QJ91K18penkE5dc1ZiNDMF6S6gA
        x9beUDzX/Qz3x6rRovByYaQDMLyXRa4nCqYtT8BAGJWaIZ+DSw3s7XZ7JcCu2lq2
        fo9q98QFvB4pRgPQyRM9aGJBeGeX4dLHK8zra8nVaIsjcfyGL+aMr7aMpKjPCfzw
        NdyACEb8ru2gS5vlD7rh/j3nU9Wx8fMif6xMeYI3GWMNLF23yYjYwtbr0sdOXswM
        iSQwtOkRAoGBAORjPg7zr0jKy4dUrCcCpu32R0ndzPQOVa7tGjsiNzf9kPC1z58H
        ebu8VVe6ZfxZw3v3xY8KzZwRQITrPw6iZFKrLkbz8v0IZPdtNTaAWnVSaseav9Zq
        V6QhUDkbyWjv/ItPvXfyyZDmvXSqnA20slV92NAgKHufW4DrRZ0r8YLXAoGBAN1c
        jDxAGjMu6ULBof/uRd3yqpBbiBw26MPm9+le+1XADOtsiCCqyH86YMRAkv7qo8eU
        msT1POGhzRHbrdgzKeFh3Pi7MHmZJ+jS9UryNSg38A8pt4DWf4tMEATzD8MgNxly
        63bEWuS2fcQlyK8mwFWRBrlwlqD2oEKLjB786HRpAoGBAIsa+1iGCjRO+Kpj4zsb
        fWsg/wi5pLTd6khSOBDeZT2gHuDODDhziCzVqDF34dhTICLophba4KL3SxHqawzR
        0kMb6mLjARQnQcAGb0vT38Tnvwv2cHP7b4gTllZCW2mkCnEbz244nZa5Q5nEtKoQ
        bjJuJVmWzLGHPWeHZW42rrIfAoGBAKHl2jsGtyLQIJJOhGlmn3rgzJagG0BneH4v
        IwpwCWqB9/EHg9hAkDtdOwDOKbR/cCG8MiXzJv/vEskI3nDNmsfYh4Dzh1SoC2Rh
        Rj32P6KWpuCwJiH4v3flvaGhE9omaaYXQteubLvyLLGU4N4ZfXoXg8+E5OX8+uEw
        pt7TIkBhAoGAIgTL5uAxtVA/ghVBoqL2rCwORO8PstepnwJ9o4aBOmXAeEBee6r4
        CipEwoDoRNAk+PSKzy2UubSbqJ98BKxZgfu5Yy4i1kPiYDThaphdpjETUTbvPhGm
        ga3Dpi5DxbvHdZeB1wlbXj0zTMXrxFCpI5sZVubOQttrIo9Jc9LZQAA=
        -----END RSA PRIVATE KEY-----
      public-key: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxXw9WTwgzNvdNYSdgjdf
        nUWgfeVfKRp3JewTWKxbRbeiCVjw5pcj5t9yntCG5KLZU4pVjPppEl3fLa/jbYup
        rPLPwqtkgcMK7drrWlLEdppD0XBvMRp1ZmYalWdHJOpY/xFD8w3NavXNAPJULD88
        MBIR/99zc9DKnfp88u+SkHjiVHLidpR5OQPP3sqiS+bsPcaBWRvHQ7r1yFe6PAyW
        hTNAMr62s+HbjkV2u7i1u8Lc6iulVhD2riM4oTndjoN8KRsf/G3nOSVvbCA0CCv9
        Tnk6H7eeZVh9o061LQxQ64hWXsCQ5lcitA1Fm+xjkrIlc/TQe38Z3WD8VD48rDAW
        LwIDAQAB
        -----END PUBLIC KEY-----