spring:
  cloud:
    gateway:
      routes:
        - id: authentication-server
          uri: lb://authentication-server
          predicates:
            - Path=/oauth/token
            - Path=/oauth/authorize
            - Path=/oauth/check_token
            - Path=/rest/api/v1/user
        - id: parcel-delivery-service
          uri: lb://parcel-delivery-service
          predicates:
            - Path=/parcel-delivery/**
          filters:
            - StripPrefix=1