spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authentication-server
    username: admin
    password: asd123
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

security:
  oauth2:
    client:
      client-id: parcel-delivery-service
      client-secret: pwd-parcel-delivery-service
      scope: read
      grant-type: client_credentials, password
      access-token-uri: http://localhost:9090/oauth/token
    resource:
      token-info-uri: http://localhost:9090/oauth/check_token